[package]
name = "cpm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "^0.3"
serde = "^1"
toml = "^0.5"

common = { path = "../common" }
